name: CI/CD Pipeline

on:
  push:
    branches: [ main ]
    tags: ['v*']
  pull_request:
    branches: [ main ]

jobs:
  build-test-package:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Install dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y build-essential cmake libgtest-dev libgmock-dev dpkg-dev debhelper git

    - name: Configure CMake
      run: cmake -B build -DCMAKE_BUILD_TYPE=Release

    - name: Build project
      run: cmake --build build --config Release

    - name: Run tests
      run: cd build && ctest --output-on-failure

    - name: Create DEB package
      run: |
        # Создаем структуру пакета
        mkdir -p package/usr/bin
        
        cp build/StrategyPatternTests package/usr/bin/
        
        # Создаем файл управления пакетом
        mkdir -p package/DEBIAN
        cat > package/DEBIAN/control <<EOF
        Package: strategy-pattern
        Version: 1.0.0
        Section: utils
        Priority: optional
        Architecture: amd64
        Maintainer: Your Name <your.email@example.com>
        Description: Strategy Pattern Example Application
         This package contains the executable for the Strategy Pattern example.
        EOF
        
        # Собираем пакет
        dpkg-deb --build package strategy-pattern.deb
        echo "DEB_PATH=$(pwd)/strategy-pattern.deb" >> $GITHUB_ENV

    - name: Upload build artifact
      uses: actions/upload-artifact@v4
      with:
        name: strategy-pattern-package
        path: |
          ${{ env.DEB_PATH }}
          build/StrategyPatternTests

  create-release:
    needs: build-test-package
    runs-on: ubuntu-latest
    if: startsWith(github.ref, 'refs/tags/')
    
