name: CI/CD Pipeline

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-test-package:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      with:
        fetch-depth: 0

    - name: Get version
      id: get_version
      run: echo "version=$(git describe --tags --always)" >> $GITHUB_OUTPUT

    - name: Install dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y build-essential cmake dpkg-dev debhelper lintian
        sudo apt-get install -y libgtest-dev libgmock-dev
        
        # Сборка и установка Google Test и Google Mock
        cd /usr/src/googletest
        sudo cmake -B build -DBUILD_GMOCK=ON -DINSTALL_GTEST=ON
        sudo cmake --build build
        sudo cmake --install build

    - name: Configure CMake
      run: cmake -B build -DCMAKE_BUILD_TYPE=Release

    - name: Build project
      run: cmake --build build --config Release

    - name: Run tests
      run: cd build && ctest --output-on-failure

    - name: Create DEB package
      run: |
        mkdir -p package/usr/bin
        cp build/StrategyPatternApp package/usr/bin/
        mkdir -p package/usr/share/strategy-pattern
        cp -r Resources package/usr/share/strategy-pattern/
        
        # Create DEB control files
        mkdir -p package/DEBIAN
        cat > package/DEBIAN/control <<EOF
        Package: strategy-pattern
        Version: ${{ steps.get_version.outputs.version }}
        Section: utils
        Priority: optional
        Architecture: amd64
        Maintainer: Your Name <your.email@example.com>
        Description: Strategy Pattern Example Application
         This package contains the executable and resources for the Strategy Pattern example.
        EOF
        
        # Build the package
        dpkg-deb --build package strategy-pattern.deb

    - name: Upload artifacts
      uses: actions/upload-artifact@v4
      with:
        name: strategy-pattern-package
        path: |
          strategy-pattern.deb
          build/StrategyPatternApp
